sudo: requiered
services:
    - docker

before_install:
    - docker build -t arkan9el/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true arkan9el/react-test npm test

after_success:
    - docker build -t arkan9el/multi-client ./client
    - docker build -t arkan9el/multi-nginx ./nginx
    - docker build -t arkan9el/multi-server ./server
    - docker build -t arkan9el/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push arkan9el/multi-client
    - docker push arkan9el/multi-nginx
    - docker push arkan9el/multi-server
    - docker push arkan9el/multi-worker

deploy:
    provider: elasticbeanstalk
    region: eu-west-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-west-1-511640615328
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY


#    deploy:
#        edge: true
#        provider: elasticbeanstalk